# SwiftLint Configuration for Anchor
# https://github.com/realm/SwiftLint

# Paths to include during linting
included:
  - Anchor
  - AnchorKit/Sources
  - AnchorMobile

# Paths to ignore during linting.
excluded:
  - AnchorKit/Tests
  - AnchorTests
  - AnchorUITests
  - Pods
  - .build
  - Carthage
  - Package.swift
  - "*/Package.swift"
  - "**/DerivedData"
  - "**/Build"
  - "**/.build"
  - "**/*.derived"
  - "**/runner.swift"
  - "**/GeneratedAssetSymbols.swift"
  - "**/*-OutputFileMap.json"
  - "**/**/runner.swift"
  - "**/DerivedSources"
  - "**/*Tests*"
  - "**/*Test*"
  - "**/PlaceCategorization.swift"  # Complex domain logic with acceptable complexity

# Rules to disable
disabled_rules:
  - trailing_whitespace # Can be auto-fixed by Xcode
  - multiple_closures_with_trailing_closure # Common and idiomatic in SwiftUI

# Rules to enable that are opt-in
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - force_try

# Customized rules
line_length:
  warning: 120  # Match CI expectations
  error: 160
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 1
    error: 1
  excluded:
    - id
    - x
    - y
    - z

# Custom rules could go here if needed in the future

# Performance and quality rules specific to location and networking code
force_cast:
  severity: error

# Allow longer parameter lists for AT Protocol request models
function_parameter_count:
  warning: 8
  error: 12