name: "SwiftLint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SwiftLint
      run: |
        brew install swiftlint
        
    - name: Run SwiftLint on All Swift Code
      run: |
        # Lint all Swift files from project root using our configuration
        # This will lint Anchor/, AnchorKit/Sources/, and AnchorMobile/ as specified in .swiftlint.yml
        swiftlint lint --config .swiftlint.yml